//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoggleWebservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoggleGame
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid fk_BoggleBoxId { get; set; }
        public int Score { get; set; }
    
        public virtual Board Board { get; set; }
    }
}
